Repository subinoybiswas/clippy, pull requests merged in 2024-06, with the labels that each got.

#23 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: gssoc, level1

#27 Feat: Added Footer Component With Github and About Us Links
  app/components/Footer.tsx
  app/page.tsx
  app/utils/abouts.png
  app/utils/github.png
Labels: gssoc, level2

#33 added the docker file along with the documentation
  Dockerfile
  README.md
Labels: gssoc, level2

#51 Added custom scroll bar for the website
  app/globals.css
Labels: gssoc, level2

#58 Create LICENSE
  LICENSE
Labels: gssoc, level1

#61 Removed duplicate close button
  app/page.tsx
Labels: gssoc, level2

#63 Implement Standardized Greeting for Closed Issues
  .github/workflows/autocomment-iss-close.yml
Labels: gssoc, level1

#66 Created A full working Form
  .env.example
  app/page.tsx
  package.json
Labels: gssoc, level3

#68 Corrected spelling mistake - fixed issue 67
  README.md
Labels: gssoc, level1

#65 changes
  app/components/getPage.tsx
Labels: gssoc, level1

#69 Added react-toastify for invalid ClippyID notification
  app/api/createClippy/route.ts
  app/api/getPage/route.ts
  app/page.tsx
  package-lock.json
  package.json
Labels: gssoc, level3

#75 Corrected spelling error#74
  app/components/Instruction.tsx
Labels: gssoc, level1

#80 fix: Added animation cursor in all files
  app/aboutus/page.tsx
  app/components/getPage.tsx
Labels: gssoc, level2

#81 About us issues fixed
  app/aboutus/page.tsx
  app/page.tsx
Labels: gssoc, level2

#83 Fixed links in readme
  README.md
Labels: gssoc, level1
